### ISSUE TITLE
eslintがカンカンでいらっしゃる

### ISSUE THREAD

**Issue by katai5plate** [katai5plate/test-gamelist-react#4]
4:1   error  Component should be written as a pure function  react/prefer-stateless-function
   4:36  error  Missing space before opening brace              space-before-blocks
   5:11  error  Missing space before opening brace              space-before-blocks
   6:5   error  Expected space(s) after "return"                keyword-spacing
   7:7   error  JSX not allowed in files with extension '.js'   react/jsx-filename-extension
   8:35  error  'var' is missing in props validation            react/prop-types
  15:22  error  A space is required before closing bracket      react/jsx-tag-spacing

**Comment by katai5plate** [comment]
7:7 error JSX not allowed in files with extension '.js' react/jsx-filename-extension

これに関しては.eslintrc以下のようにすれば治るっぽい
```js
{
  "extends": "airbnb",
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
  }
}
```
https://qiita.com/romiogaku/items/27929395e3133b514516

ymlに直すとこうだと思われ
```yml
extends: airbnb
env:
  browser: true
rules:
  react/jsx-filename-extension:
    - 1
    - { "extensions": [".js", ".jsx"] }
```

**Comment by katai5plate** [comment]
> 8:35 error 'var' is missing in props validation react/prop-types

prop-typesが必要らしい。
- https://api.wp-kyoto.net/refactor-react-componet-by-eslint/#7261021error_8216type8217_is_missing_in_props_validation
- https://github.com/yannickcr/eslint-plugin-react/issues/1257

```batch
npm i -S prop-types
rem ↓はeslintのエラーが起きたとき
rem npm i -D eslint-plugin-jsx-a11y@latest
```
- [`-S`は`--save`の略。`-D`は`--save-dev`の略。](http://yosuke-furukawa.hatenablog.com/entry/2014/06/10/100410)

そして
```jsx
class Hello extends React.Component {
  render() {
    return (
      <div className="hellowa">
        <h1>Hello-WA, {this.props.var}</h1>
      </div>
    );
  }
}
```
を
```jsx
class Hello extends React.Component {
  render() {
    return (
      <div className="hellowa">
        <h1>Hello-WA, {this.props.var}</h1>
      </div>
    );
  }
}
Hello.propTypes = {
  var: PropTypes.string,
};
Hello.defaultProps = {
  var: 'your-name',
};
```
に書き換える

**Comment by katai5plate** [comment]
> 4:1 error Component should be written as a pure function react/prefer-stateless-function

Stateの変更がないコンポーネントはclassで定義してはいけないらしい
https://api.wp-kyoto.net/refactor-react-componet-by-eslint/#316_error_Component_should_be_written_as_a_pure_function

一時的に警告止まりにするなら、ソースに直接
```js
/* eslint react/prefer-stateless-function: 1 */
```
を書き込めばいい。

永久的にオフにするなら、`.eslintrc.yml`をこうする
```yml
extends: airbnb
env:
  browser: true
rules:
  react/jsx-filename-extension:
    - 1
    - { "extensions": [".js", ".jsx"] }
  react/prefer-stateless-function:
    - 1
```
